# Site settings
title: Samtools
email: your-email@domain.com
description: "Samtools"
baseurl: "http://www.htslib.org"
url: "http://www.htslib.org"
twitter_username: htslib
exclude: [CNAME]

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
gems: [jekyll-sitemap]
